- hosts: Dev, QA
  user: service
  become: yes
  connection: ssh
  gather_facts: yes

  tasks:
    - name: cloning Dockerfile and docker-compose.yaml file
      command: git clone https://github.com/aakashchavhan/devops.git

    - name: install docker
      command: yum install docker -y

    - name: start docker
      command: systemctl start docker

    - name: copy compose file
      command: mv docker-compose.yaml Dockerfile /home/service/

    - name: run docker-compose file
      command: docker-compose up -d
